<?php
namespace ProcessWire;

class TrelloWireCard extends WireData implements Module
{
    public static function getModuleInfo()
    {
        return [
            'title' => __('Trello Wire Card'),
            'summary' => __('TrelloWire: Card component (installed automatically).'),
            'author' => "Moritz L'Hoest",
            'version' => '0.1.0',
            'icon' => 'trello',
            'requires' => [
                'PHP>=7.2',
            ],
        ];
    }

    /**
     * Set the page this card belongs to.
     *
     * @param Page $page
     * @return void
     */
    public function ___setPage(Page $page): void
    {
        $this->set('page', $page);
    }

    /**
     * Set this cards ID (only used for cards that already exist in Trello).
     *
     * @param string $id
     * @return void
     */
    public function ___setId(string $id): void
    {
        $this->set('id', $id);
    }

    /**
     * Set the ID of the list this card belongs to.
     *
     * @param string $idList
     * @return void
     */
    public function ___setList(string $idList): void
    {
        $this->set('list', $idList);
    }

    /**
     * Set the title / name of this card.
     *
     * @param string $title
     * @return void
     */
    public function ___setTitle(string $title): void
    {
        $this->set('title', $title);
    }

    /**
     * Set the body / description of this card.
     *
     * @param string $body
     * @return void
     */
    public function ___setBody(string $body): void
    {
        $this->set('body', $body);
    }

    /**
     * Set the IDs of labels belonging to this cards. Note that label IDs are
     * specific to each board.
     *
     * @param array $labelIds
     * @return void
     */
    public function ___setLabels(array $labelIds): void
    {
        $this->set('labels', $labelIds);
    }
}
